In [3]:
import numpy as np

In [16]:
score = np.random.randint(40,100,(10,5))
test_score = score[:5,:]

# ndarry运算

In [12]:
test_score[test_score > 60] = 1
test_score

array([[ 1, 53, 51,  1, 50],
       [ 1,  1,  1,  1, 56],
       [ 1, 55,  1,  1,  1],
       [42,  1, 59, 41, 50],
       [ 1, 54,  1,  1,  1]])

In [13]:
np.any(test_score > 90)

True

In [14]:
np.all(test_score > 90)

False

In [17]:
temp = score[:4 ,:4]
temp

array([[54, 59, 99, 43],
       [49, 77, 97, 52],
       [61, 44, 81, 90],
       [58, 49, 84, 77]])

In [19]:
np.where(temp>60 , 1, 0)

array([[0, 0, 1, 0],
       [0, 1, 1, 0],
       [1, 0, 1, 1],
       [0, 0, 1, 1]])

In [20]:
temp1 = score[:4,:4]
temp1

array([[54, 59, 99, 43],
       [49, 77, 97, 52],
       [61, 44, 81, 90],
       [58, 49, 84, 77]])

In [22]:
np.max(temp,axis=1)

array([99, 97, 90, 84])

In [23]:
np.argmax(temp, axis=1)

array([2, 2, 3, 2], dtype=int64)

# 数组间的运算

In [25]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])

In [26]:
arr1 + 1

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [27]:
lista = [1 ,2, 3, 4]

In [28]:
lista + 1 

TypeError: can only concatenate list (not "int") to list

In [29]:
arr1 / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ]])

In [30]:
lista / 2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [31]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])

In [32]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])

In [33]:
arr1 + arr2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])