In [1]:
import numpy as np

In [3]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
a = np.array([[1,2,3],[1,2,3]])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [8]:
b = np.array(a)
b

array([[1, 2, 3],
       [1, 2, 3]])